import { Nunito } from 'next/font/google'
import './globals.css'
import { Navbar, Footer } from '@/components'
import { WhatsappIcon } from '@/modules'

const nunito = Nunito({ subsets: ['latin'], weight: ['200','300','400','500','600','700','800','900','1000'], style: 'normal' })

export const metadata = {
  title: 'Poderify',
  description: 'Generated by create next app',
  keywords: ['','',''],
  url: 'https://poderify.com',
  type: 'website',
}


export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${nunito.className} bg-body-gradient`}>
        < Navbar />
        <WhatsappIcon />
        {children}
        <div className='mt-12'>
          < Footer />
        </div>
      </body>
    </html>
  )
}
